# fly.toml app configuration file generated for what-the on 2023-05-17T16:26:24+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "what-the"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
